# Set status color
%if "#{==:#{host},BiscuitVOID}"
   set -g status-style bg=purple
%elif "#{==:#{host},BiscuitVPS}"
   set -g status-style bg=orange
%elif "#{==:#{host},localhost}"
   set -g status-style bg=cyan,fg=black
%else
   set -g status-style bg=green
%endif

bind-key j run-shell $HOME/.config/tmux/tmux-popup

bind-key b set status
bind-key v copy-mode

set-window-option -g mode-keys vi

# Split panes using | and - and make them open in the current path
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Also apply to creating new windows
bind C new-window -c "#{pane_current_path}"
