# Set status color
%if "#{==:#{host},BiscuitVOID}"
   set -g status-style bg=purple
%elif "#{==:#{host},BiscuitVPS}"
   set -g status-style bg=orange
%else
   set -g status-style bg=green
%endif

bind-key j run-shell tmux-popup
bind-key b set status
