#!syntax bash
# Reset sxhkd
super + shift + s
	pkill -10 sxhkd

# Open terminal
super + Return
	st

# Kill window manager

super + ctrl + q
    logout-wm

# Open terminal with dvtm
super + Shift_R
    st -e tmux new -A -s session

# Lock Screen
super + slash
    light-locker-command -l

# Open text editor with sxhkrc
super + shift + slash
	st -e nvim ~/.config/sxhkd/sxhkdrc

# Toggle keyboard LED
Scroll_Lock
    xset q | grep -q 'Scroll Lock: off' && xset led named 'Scroll Lock' || xset -led named 'Scroll Lock'

# toggle fullscreen
#super + shift + f
#	xdotool getwindowfocus windowstate --toggle FULLSCREEN


# Close current window
# super + q
#     xdotool getwindowfocus windowquit

# Force kill current program
super + shift + q
    kill -9 `xdotool getwindowfocus getwindowpid`

# Control audio volume
XF86AudioRaiseVolume
	pactl set-sink-volume @DEFAULT_SINK@ +5%
XF86AudioLowerVolume
	pactl set-sink-volume @DEFAULT_SINK@ -5%
XF86AudioMute
	pactl set-sink-mute @DEFAULT_SINK@ toggle

super + equal
	pactl set-sink-volume @DEFAULT_SINK@ +5%
super + minus
	pactl set-sink-volume @DEFAULT_SINK@ -5%
super + plus
	pactl set-sink-mute @DEFAULT_SINK@ toggle

## Control backlight
#XF86MonBrightnessUp
#	light +
#XF86MonBrightnessDown
#	light -

# Manage networking
super + n
	networkmanager_dmenu

# Toggle picom
super + shift + c
    picom-toggle &
	# if pgrep picom; then pkill picom ; else picom -b ; fi

#OpenTableDriver
super + shift + t
    otd-toggle

# Open bluetui
super + shift + b
	st -e bluetui

# Open cmus
super + shift + m
	st -e cmus

# Open program
super + d
    dmenu_history -l 20
super + p
	rofi -show drun

# Open browser
super + w
    chromium
super + shift + w
	firefox

# Open pulsemixer
super + a
	st -e pulsemixer

# Open htop
super + shift + h
	st -e htop

# Open Vifm
super + v
	st -e vifm

# Open PCManFm
super + shift + v
	pcmanfm

# Run screen script
super + ctrl + s
	screen

# Vimwiki
super + shift + n
    obsidian &

# Autoclicker
super + KP_Insert
	if pgrep autoclicker; then pkill autoclicker & else autoclicker; fi
# Hold left mouse
super + KP_Delete
    xdotool mousedown 1
# Hold right mouse
super + KP_End
    xdotool mousedown 3
    # if [ -e "/tmp/clicked.lock" ]; then xdotool mouseup 1; rm "/tmp/clicked.lock"; else xdotool mousedown 1; touch "/tmp/clicked.lock"; fi
# Hold "W" key
# super + KP_Down
#     xdotool keydown w

# Screenshot
Print
    mkdir -p ~/Pictures/screenshots ; cd ~/Pictures/screenshots && scrot

# Play youtube
super + y
    yt -r

#=========# Controller #===========#
#Kill window
XF86AudioPrev
    kill -9 $(xdo pid)

# Press Ctrl-Tab
XF86AudioPlay
    xdotool keyup XF86AudioPlay key --clearmodifiers keydown ctrl keydown Tab keyup Tab keyup ctrl
    # xdotool keyup XF86AudioPlay key --clearmodifiers key Pause
